version: "3.7"
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            APP_HTTP_PORT: 80
        ports:
            - "8080:80"
        depends_on:
            - postgres
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_USER: admin
            POSTGRES_DB: keycloak
        volumes:
            - ./docker/volumes/postgres/data:/var/lib/postgresql/data

    keycloak:
        depends_on:
            - postgres
        image: jboss/keycloak
        restart: always
        ports:
            - 8081:8080
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            DB_VENDOR: postgres
            DB_ADDR: postgres
            DB_USER: admin
            DB_PASSWORD: mysecretpassword
