http:
    server:
        # The port is set, too, in Dockerfile, see also there
        port: 8080

swagger:
    route: api
    title: Sample API App
    description: This is a sample server for a pet store.
    termsOfService: http://example.com/terms/
    contact:
        name: API Support
        url: http://www.example.com/support
        email: support@example.com
    license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0.html
    version: 1.0.0

healthcheck:
    url: /health
    ping:
        google: https://www.google.com

database:
    type: pg
    host: localhost
    port: 5432
    username: admin
    password: mysecretpassword
    database: backend
    entities:
        - '**/*.entity{.ts,.js}'
    synchronize: true
